dist: trusty
sudo: false
language: elixir
elixir: 1.5.1
otp_release: '20.0'
env: MIX_ENV=test
script: mix coveralls.travis
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ecd75f033a429fcd86e
    on_success: change
    on_failure: always
    on_start: never
