apiVersion: v1
kind: Service
metadata:
  name: open-budget-service
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: open-budget
  type: LoadBalancer